spring:
  data:
    redis:
      host: redis-orders
      port: 6379
      password: ${REDIS_ORDERS_PASSWORD}
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
      key-prefix: "app:"
      use-key-prefix: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 3
        max.in.flight.requests.per.connection: 1
        enable.idempotence: true
        compression.type: snappy
        linger.ms: 20
        batch.size: 32768
        request.timeout.ms: 30000
        delivery.timeout.ms: 60000
  cloud:
    compatibility-verifier:
      enabled: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${ORDER_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
security:
  jwt:
    secret: ${JWT_SECRET}
springdoc:
  override-with-generic-response: false
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,kafka
  metrics:
    export:
      prometheus:
        enabled: true
feign:
  circuit breaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
restaurant:
  service:
    url: ${RESTAURANT_ENDPOINT}
resilience4j:
  circuitbreaker:
    instances:
      restaurant-service:
        registerHealthIndicator: true
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowSize: 10